### ISSUE TITLE
PHPCaptcher not shown in user registration process

### ISSUE THREAD

**Issue by jheinitz** [pstimpel/phpcaptchapiwigo#1]
Hello,

I installed, activated and configured your plugin for my site (https://www.ebo-eisenbahn.de). It works fine for the contact form and the guestbook. However, it is not shown for the new user registration process, but it must be active in the background. When I click the "Register" button, IU receive the following error messages on my page. 

Notice: Undefined index: captcha_hash in /raid1/www/vhosts/www.ebo-eisenbahn.de/htdocs/plugins/phpcaptchapiwigo/include/register.inc.php on line 32

Notice: Undefined index: captcha_code in /raid1/www/vhosts/www.ebo-eisenbahn.de/htdocs/plugins/phpcaptchapiwigo/include/register.inc.php on line 35

Notice: Undefined index: captcha_code in /raid1/www/vhosts/www.ebo-eisenbahn.de/htdocs/plugins/phpcaptchapiwigo/include/register.inc.php on line 39

And I see a red box with the content "Invalid Captcha"

What is wrong here? Any help is appreciated.

Kind regards and merry christmas.

Jens

**Comment by pstimpel** [comment]
missed at the time the issue was opened, cannot reproduce anymore. Sorry for missing the issue in the first place
